version: '3.9'

services:
    db:
        container_name: database
        image: mongo
        ports:
            - ${DB_PORT}:${DB_PORT}
        restart: always
    
    api_production:
        container_name: ubicar_api_production
        build:
            context: .
            dockerfile: Dockerfile
        image: ubicar-api-production
        ports: 
            - ${PORT}:${PORT}
        links:
            - db
        depends_on:
            - db
        restart: always