name: Docker Image CI

on:
  push:
    branches: [ "dev-alvaro-ts" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Remove current containers
      run: docker rm ubicar_api_dev -f
    - name: Copy env file
      run: cp /home/ubicar/.env ./
    - name: Install dependencies
      run: npm install
    - name: Restart containers
      run: npm run compose:dev
